dir: "internal/mocks/{{.PackageName}}"
disable-version-string: True
with-expecter: True
packages:
  io:
    interfaces:
      Reader:
  github.com/dsh2dsh/edgar/client:
    interfaces:
      HttpRequestDoer:
      Limiter:
  github.com/dsh2dsh/edgar/cmd:
    interfaces:
      Storage:
  github.com/dsh2dsh/edgar/cmd/internal/repo:
    interfaces:
      Postgreser:
