dir: "internal/mocks/{{.PackageName}}"
disable-version-string: True
with-expecter: True
packages:
  io:
    interfaces:
      Reader:
  github.com/jackc/pgx/v5:
    interfaces:
      Tx:
  github.com/dsh2dsh/edgar/client:
    interfaces:
      HttpRequestDoer:
      Limiter:
  github.com/dsh2dsh/edgar/cmd/db:
    interfaces:
      Repo:
  github.com/dsh2dsh/edgar/cmd/download:
    interfaces:
      Storage:
  github.com/dsh2dsh/edgar/internal/repo:
    interfaces:
      Postgreser:
