dir: "{{.InterfaceDir}}/internal/mocks"
disable-version-string: True
outpkg: "mocks"
with-expecter: True
packages:
  io:
    config:
      dir: "client/internal/mocks"
    interfaces:
      Reader:
  github.com/dsh2dsh/edgar/client:
    interfaces:
      HttpRequestDoer:
      Limiter:
