// Code generated by mockery. DO NOT EDIT.

package client

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLimiter is an autogenerated mock type for the Limiter type
type MockLimiter struct {
	mock.Mock
}

type MockLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimiter) EXPECT() *MockLimiter_Expecter {
	return &MockLimiter_Expecter{mock: &_m.Mock}
}

// Wait provides a mock function with given fields: _a0
func (_m *MockLimiter) Wait(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLimiter_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockLimiter_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockLimiter_Expecter) Wait(_a0 interface{}) *MockLimiter_Wait_Call {
	return &MockLimiter_Wait_Call{Call: _e.mock.On("Wait", _a0)}
}

func (_c *MockLimiter_Wait_Call) Run(run func(_a0 context.Context)) *MockLimiter_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLimiter_Wait_Call) Return(_a0 error) *MockLimiter_Wait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLimiter_Wait_Call) RunAndReturn(run func(context.Context) error) *MockLimiter_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLimiter creates a new instance of MockLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimiter {
	mock := &MockLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
